### ISSUE TITLE
Should it work with webpack MF plugin?

### ISSUE THREAD

**Issue by ignatiqq** [theKashey/webpack-imported#11]
Hi, thanks for your amazing library. But when I use it I am facing an issue with "webpack_sharing_consume_default" chunks which should be loaded manually using "module federation" plugin. 

Imported plugin generates "chunks"['chunkName'].load" definitions for them but "webpack_shared_modules" chunks are missing at the "chunkMap". 

So, when I try to use import resources with any chunk (if it includes any "shared" modules), it throws an error in the "flattenType" function because it doesn't have a definition in "chunksMap". 

Can we somehow provide a filter function using a library? Thank you!

**Comment by theKashey** [comment]
Hey, a minimal example would be great. Or at least just share the raw error

**Comment by ignatiqq** [comment]
@theKashey Sorry about that. It was an issue on my side

**Comment by theKashey** [comment]
No worries, but this plugin is not MF-aware in any case.
